name: Stable lints

# We only run these lints on trial-merges of PRs to reduce noise.
on: pull_request

jobs:
  clippy:
    name: Clippy (1.51.0)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0
          components: clippy
          override: true
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy (1.51.0)
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features cli --all-targets -- -D warnings
